kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config
  namespace: testing
data:
  users-provider-config:
    database.username=app
    database.password=pass
    database.host=postgres
    database.port=5432
    database.database=db
    database.appSchema=users_provider
    server.port=9000
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: testing
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRESQL_USERNAME: app
  POSTGRESQL_PASSWORD: pass
  POSTGRESQL_DATABASE: db